sudo: required
dist: xenial

services:
  - docker

git:
  depth: 5

jobs:
  include:
    - stage: build prometsource/base image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t base ./docker/base/.
      - docker-compose up -d --build base
      - docker-compose run base /bin/bash -c 'cat /etc/os-release' > "release"
      - source release
      - ver1=${PRETTY_NAME// LTS}
      - ver1=${ver1// /-}
      - ver1=${ver1,,}
      - ver1=${ver1/$'\r'/}
      - ver2=${VERSION_ID/$'\r'/}
      - docker tag base prometsource/base
      - docker tag base prometsource/base:$ver1
      - docker tag base prometsource/base:ubuntu-$ver2
      - docker push prometsource/base
      - docker push prometsource/base:$ver1
      - docker push prometsource/base:ubuntu-$ver2
    - stage: build prometsource/apache2 image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t apache2 ./docker/apache2/.
      - docker-compose up -d --build apache2
      - docker-compose run apache2 /bin/bash -c 'cat /etc/os-release' > "release"
      - source release
      - ver1=${PRETTY_NAME// LTS}
      - ver1=${ver1// /-}
      - ver1=${ver1,,}
      - ver1=${ver1/$'\r'/}
      - ver2=${VERSION_ID/$'\r'/}
      - docker tag apache2 prometsource/apache2
      - docker tag apache2 prometsource/apache2:$ver1
      - docker tag apache2 prometsource/apache2:ubuntu-$ver2
      - docker push prometsource/apache2
      - docker push prometsource/apache2:$ver1
      - docker push prometsource/apache2:ubuntu-$ver2
